// <auto-generated />
namespace Otel_Rezervasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OtelVeriTabaniOlusturuldu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OtelVeriTabaniOlusturuldu));
        
        string IMigrationMetadata.Id
        {
            get { return "201902071627462_OtelVeriTabaniOlusturuldu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
